version: 0.2

phases:
  install:
    commands:
#      - npm i npm@latest -g
#      - pip install --upgrade pip
#      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - yarn install
  build:
    commands:
      - echo Build Phase
      - yarn build
      - yarn generate
  post_build:
    commands:
      - echo PostBuild Phase
      - echo $S3_BUCKET
      - aws s3 sync ./dist S3://GIT $S3_BUCKET
